from .base_locators import COOKIE_CONSENT_LOCATORS, MODAL_CLOSE_LOCATORS, GENERIC_SEARCH_LOCATORS
from .google_play_locators import (
    PLAY_STORE_SEARCH_BAR, PLAY_STORE_SEARCH_BUTTON,
    PLAY_STORE_APP_CARDS, PLAY_STORE_APP_TITLE, PLAY_STORE_APP_DEVELOPER, PLAY_STORE_APP_RATING
)
from .youtube_locators import (
    YOUTUBE_SEARCH_BAR, YOUTUBE_SEARCH_BUTTON,
    YOUTUBE_VIDEO_CARDS, YOUTUBE_VIDEO_TITLE, YOUTUBE_CHANNEL_NAME
)
